-- http://www.hsqldb.org/doc/guide/ch09.html#drop_table-section
drop table customer if exists;

-- http://www.hsqldb.org/doc/guide/ch09.html#create_table-section
create table if not exists customer (
 id bigint generated by default as identity (start with 1),
 first_name varchar(255),
 last_name varchar(255), primary key (id)
 );
